# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(433, 297)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(70, 20, 310, 16))
        self.label_6.setObjectName("label_6")
        self.count = QtWidgets.QPushButton(self.centralwidget)
        self.count.setGeometry(QtCore.QRect(160, 250, 93, 28))
        self.count.setObjectName("count")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 50, 369, 181))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.ruble = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.ruble.setObjectName("ruble")
        self.gridLayout.addWidget(self.ruble, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 1, 1, 1)
        self.dinar = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.dinar.setObjectName("dinar")
        self.gridLayout.addWidget(self.dinar, 3, 0, 1, 1)
        self.euro = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.euro.setObjectName("euro")
        self.gridLayout.addWidget(self.euro, 2, 0, 1, 1)
        self.rial = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.rial.setObjectName("rial")
        self.gridLayout.addWidget(self.rial, 4, 0, 1, 1)
        self.dollar = QtWidgets.QPlainTextEdit(self.layoutWidget)
        self.dollar.setObjectName("dollar")
        self.gridLayout.addWidget(self.dollar, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "Введите количество рублей и нажмите «Посчитать»"))
        self.count.setText(_translate("MainWindow", "Посчитать"))
        self.label_3.setText(_translate("MainWindow", "кувейтский динар"))
        self.label_5.setText(_translate("MainWindow", "иранский риал"))
        self.label_4.setText(_translate("MainWindow", "доллар США"))
        self.label_2.setText(_translate("MainWindow", "евро"))
        self.label.setText(_translate("MainWindow", "российский рубль"))
